# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
warnings_are_errors: false
cache: packages
before_install:
  - cd packages/packageFormationR
  - Rscript -e 'install.packages("testthat", lib="/home/travis/R-bin/lib/R/library/")'
