setwd(homeS)
require(measurements)
require(zoo)
require(RODBC)
require(magrittr)





connectName <- "dela.mayari"
db <- odbcConnect(connectName, case="postgresql",  believeNRows = F )
odbcQuery(db,paste("SET search_path=", ROOT_SCHEME, sep = ""))

# crée les vues pour utilisation ultérieures
sqlQ <- readChar("carbonModelling/scripts/sql/Csopra/SimulResultsView.sql", nchars=1e6)
sqlQuery(db, sqlQ)


predObs <- sqlQuery(db, "SELECT * FROM dm_csopra_simulations.predObs_AIAL
		    WHERE model <> 'ORCHIDEE'
")
require(ggplot2)
require(plotly)
predObs$site <- substr(predObs$id_profil_aial, 1, 2)

#deltaC
p <- ggplot(data = predObs, aes(x = deltasocobs, y = deltasocsim))  +
     geom_abline(intercept = 10 * (-1:1), color = "grey", slope = 1) +
     geom_point(aes(text = paste("lala:", year)))+
     geom_line(aes(color = site), size = 0.3, arrow = arrow(length = unit(0.1,"cm")))+
     geom_segment(aes(xend=deltasocobs, yend=deltasocsim, color = site), size = 0.3, arrow = arrow(length = unit(0.1,"cm")))+
#     geom_smooth() +
     facet_wrap(~ model)
ggplotly(p)



library(plotly)
set.seed(100)
d <- diamonds[sample(nrow(diamonds), 1000), ]
plot_ly(d, x = ~carat, y = ~price, color = ~carat,
size = ~carat, text = ~paste("Clarity: ", clarity))



M <- gvisMotionChart(Fruits, 'Fruit', 'Year',
         options=list(width=400, height=350))
plot(M)

predObsSub <- predObs[predObs$id_profil_aial %in% c("FAG_L12"),
		      c("model", "deltasocobs", "deltasocsim", "year", "id_profil_aial")]
M <- gvisMotionChart(predObsSub, 'model', 'year')

M <- gvisMotionChart(predObsSub, idvar = "model", timevar = "year", xvar = "deltasocobs",
  yvar = "deltasocsim", colorvar = "id_profil_aial")
#          options=list(width=400, height=350))
plot(M)
table(predObsSub[, c("model", "year", "id_profil_aial")])


library(googleVis)
G1 <- gvisGeoChart(Exports, locationvar='Country', colorvar='Profit')

sink("output.html")
cat(G1)
sink(fileConn)

plot(G1)


